plugins {
    id 'java'
}

group = 'tsarik.sergei'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.microsoft.playwright:playwright:1.57.0'
    // Source: https://mvnrepository.com/artifact/org.testng/testng
    testImplementation("org.testng:testng:7.12.0")
}


test {
        useTestNG()
    }
