plugins {
    id 'java'
}

group = 'tsarik.sergei'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Source: https://mvnrepository.com/artifact/com.codeborne/selenide
    implementation group: 'com.codeborne', name: 'selenide', version: '7.14.0'
    // Source: https://mvnrepository.com/artifact/org.testng/testng
    testImplementation("org.testng:testng:7.12.0")
}


test {
        useTestNG()
    }
